# Generated by Django 5.0.4 on 2024-06-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='courses',
            name='total_sem',
            field=models.IntegerField(default=6, max_length=2),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Class.courses')),
                ('hod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Class.hod')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quiz_name', models.CharField(default='Quiz', max_length=50)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Class.subject')),
            ],
        ),
    ]
