# Generated by Django 5.0.4 on 2024-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0004_rename_subject_id_notes_subject_courses_total_sem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='total_sem',
            field=models.IntegerField(default=6),
        ),
    ]
