# Generated by Django 5.0.4 on 2024-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0005_alter_courses_total_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
