# Generated by Django 5.0.4 on 2024-06-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0007_alter_branch_branch_name_alter_courses_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Class.courses'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='hod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Class.hod'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Class.courses'),
        ),
    ]
