# Generated by Django 5.0.4 on 2024-06-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0008_alter_branch_course_alter_branch_hod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Note Title', max_length=50),
        ),
    ]
